### ISSUE TITLE
Provisioning fails on php5-common installation

### ISSUE THREAD

**Issue by nmeirik** [kleiram/vagrant-symfony#24]
Vagrant version: 1.7.4
Ansible version: 2.0.0
Python version: 2.7.10
VirtualBox version: 4.3.16
OS: OS X 10.10.5

When running `vagrant up` the Ansible provisioning fails on the task `php5-common`. The error is:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: argument of type 'NoneType' is not iterable
fatal: [default]: FAILED! => {"failed": true, "stdout": ""}
```

If I run the ansible script standalone, with the `-vvv` flag, I get the following traceback:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/Users/eirik/ansible/lib/ansible/executor/process/worker.py", line 117, in run
    executor_result = TaskExecutor(host, task, job_vars, play_context, self._new_stdin, self._loader, shared_loader_obj).run()
  File "/Users/eirik/ansible/lib/ansible/executor/task_executor.py", line 92, in run
    item_results = self._run_loop(items)
  File "/Users/eirik/ansible/lib/ansible/executor/task_executor.py", line 203, in _run_loop
    items = self._squash_items(items, task_vars)
  File "/Users/eirik/ansible/lib/ansible/executor/task_executor.py", line 241, in _squash_items
    if templar._contains_vars(name):
  File "/Users/eirik/ansible/lib/ansible/template/__init__.py", line 337, in _contains_vars
    return self.environment.block_start_string in data or self.environment.variable_start_string in data
TypeError: argument of type 'NoneType' is not iterable

fatal: [default]: FAILED! => {"failed": true, "stdout": ""}
```

Any idea what could be causing this?

**Comment by kleiram** [comment]
Maybe the Python version? Since it looks to be an issue in Ansible itself. What version of Python are you using?

**Comment by nmeirik** [comment]
I have since moved on to other means of provisioning, so I won't be investigating this issue further. Sorry. Closing.
